name: Release glance chart

on:
  push:
    branches:
      - master
    paths:
      - charts/glance/Chart.yaml

permissions:
  packages: write

jobs:
  helm:
    name: Publish helm chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 1

      - name: Login to ghcr.io
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Push chart
        run: |
          VERSION="$(yq -rj .version charts/glance/Chart.yaml)"

          helm package charts/glance
          helm push "glance-${VERSION}.tgz" "oci://ghcr.io/${{ github.repository }}/chart"
