name: Release glance chart

on:
  push:
    branches:
      - master
    paths:
      - charts/glance/Chart.yaml

permissions:
  packages: write

jobs:
  helm:
    name: Publish helm chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Push chart
        run: |
          VERSION="$(yq -rj .version charts/glance/Chart.yaml)"

          helm package charts/glance
          helm push "glance-${VERSION}.tgz" "oci://ghcr.io/${{ github.repository }}/chart"
