name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  container:
    name: Publish container image
    runs-on: ubuntu-latest

    steps:
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 1

      - name: Container Tags
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6
        with:
          images: |
            ghcr.io/${{ github.repository }}/glance-k8s
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}

      - uses: redhat-actions/buildah-build@27e5954dfd56a621f706827f2de689dc955e8711 # v3
        id: build-image
        with:
          tags: ${{ steps.meta.outputs.tags }}
          archs: amd64, arm64
          containerfiles: |
            ./Containerfile

      - uses: redhat-actions/push-to-registry@94ade333c38ecc0e60e94785125d9a52ca423b37 # v3
        with:
          tags: ${{ steps.build-image.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

  helm:
    name: Publish helm chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 1

      - name: Login to ghcr.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Push chart
        run: |
          helm package charts/glance-k8s --version ${{ github.ref_name }} --app-version ${{ github.ref_name }}
          helm push "glance-k8s-${{ github.ref_name }}.tgz" "oci://ghcr.io/${{ github.repository }}/chart"
